services:
  # A Python web service for the backend API
  - type: web
    name: meal-planner-api
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r mealPlannerBackend/requirements.txt"
    startCommand: "gunicorn --chdir mealPlannerBackend app:app"
    envVars:
      - key: MONGODB_URI
        sync: false # This will be set as a secret in the Render dashboard
      - key: PYTHON_VERSION
        value: 3.11.4

  # A Static Site for the frontend
  - type: static_site
    name: meal-planner-frontend
    plan: free
    region: oregon
    # The root of our static assets
    staticPublishPath: ./mealPlannerFrontend
    # Add rewrite rules for the frontend
    rewrites:
      # Proxy API requests to the backend service
      - source: /api/:path*
        destination: https://meal-planner-api.onrender.com/:path*
      # Fallback for Single-Page App routing
      - source: /*
        destination: /index.html
