services:
  # A Python web service
  - type: web
    name: meal-planner-backend
    env: python
    plan: free # You can choose a paid plan for more resources
    # The region to deploy to.
    region: oregon
    # Tell Render how to build your project.
    buildCommand: "pip install -r mealPlannerBackend/requirements.txt"
    # The command to start your Gunicorn server.
    startCommand: "gunicorn --chdir mealPlannerBackend app:app"
    envVars:
      - key: MONGODB_URI
        sync: false # Keep this secret
      - key: PYTHON_VERSION
        value: 3.11.4 # Specify a Python version

  # A static site for the frontend
  - type: web
    name: meal-planner-frontend
    plan: free
    region: oregon
    # Where the static files are located.
    staticPublishPath: mealPlannerFrontend
    # Rewrite all requests to index.html for a Single-Page App experience.
    staticRewrite:
      source: /
      destination: /index.html
