from pymongo import MongoClient
import os

# MongoDB setup
URI = os.environ.get("MONGODB_URI")
client = MongoClient(URI)
db = client['mealPlannerDB']
dishes_collection = db['dishes']

# Clear existing data
dishes_collection.delete_many({})

data = {
    'southIndian': [
        {'name': 'Dosa', 'cuisine': 'southIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnKX5f_qUT4c-LgQ0ElywavoKMWPxyHcUqJA&usqp=CAU', 'meal_type': ['breakfast', 'dinner'], 'cooking_time': 30, 'ingredients': ['rice flour', 'urad dal', 'potato', 'onion', 'green chili', 'mustard seeds', 'turmeric', 'salt', 'oil'], 'description': 'A crispy and savory pancake from South India, typically served with a spicy potato filling.', 'recipe': '1. Make the batter by soaking and grinding rice and urad dal. 2. Ferment the batter overnight. 3. Prepare the potato filling with boiled potatoes, onions, and spices. 4. Spread the batter on a hot griddle to make a thin pancake. 5. Add the filling, fold, and serve hot.'},
        {'name': 'Idli', 'cuisine': 'southIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx0-KthRy1thy1LXZmmD59JTTUnou9mmvjQw&usqp=CAU', 'meal_type': ['breakfast'], 'cooking_time': 20, 'ingredients': ['idli rice', 'urad dal', 'poha', 'salt', 'oil'], 'description': 'Soft, fluffy steamed rice cakes, a popular and healthy breakfast item.', 'recipe': '1. Prepare batter by soaking and grinding idli rice and urad dal. 2. Ferment overnight. 3. Pour the batter into idli molds. 4. Steam for 10-15 minutes. 5. Serve hot with chutney and sambar.'},
        {'name': 'Medu Wada', 'cuisine': 'southIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa176Oi0JdD8swTqvfkbZLNtQ1-Yn1yOs4XA&usqp=CAU', 'meal_type': ['breakfast', 'snack'], 'cooking_time': 40, 'ingredients': ['urad dal', 'onion', 'green chili', 'ginger', 'curry leaves', 'salt', 'oil'], 'description': 'A crispy, savory donut-shaped fritter made from lentil batter.', 'recipe': '1. Soak urad dal and grind to a fluffy batter. 2. Add chopped onion, green chili, ginger, and curry leaves. 3. Shape the batter into donut forms. 4. Deep fry until golden brown. 5. Serve hot.'},
        {'name': 'Upma', 'cuisine': 'southIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsSE5T7QDt07pFaxgRkgfPVXg7sYJtguyIog&usqp=CAU', 'meal_type': ['breakfast'], 'cooking_time': 15, 'ingredients': ['semolina', 'onion', 'mustard seeds', 'curry leaves', 'green chili', 'ginger', 'oil', 'salt'], 'description': 'A thick and savory porridge made from dry-roasted semolina or coarse rice flour.', 'recipe': '1. Roast semolina until lightly fragrant. 2. Sauté mustard seeds, onion, chili, and ginger in oil. 3. Add water and bring to a boil. 4. Slowly add roasted semolina while stirring continuously. 5. Cook until thick and serve hot.'}
    ],
    'northIndian': [
        {'name': 'Paneer Butter Masala', 'cuisine': 'northIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgBgc6jNnQgRH0ql3etygKkWtpddQSLsDuAQ&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 45, 'ingredients': ['paneer', 'onion', 'tomato', 'cashews', 'cream', 'butter', 'ginger', 'garlic', 'red chili powder', 'turmeric', 'garam masala'], 'description': 'A rich and creamy curry made with paneer, tomatoes, butter, and a special spice blend.', 'recipe': '1. Make a paste of onion, tomato, and cashews. 2. Sauté the paste in butter with ginger-garlic paste. 3. Add spices and cook until oil separates. 4. Add paneer cubes and cream. 5. Simmer for a few minutes and serve.'},
        {'name': 'Aloo Gobi', 'cuisine': 'northIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8rKoxZdsneyodyJZGTB6zYus-ZEVPBXVYGw&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 35, 'ingredients': ['potato', 'cauliflower', 'onion', 'tomato', 'ginger', 'garlic', 'turmeric', 'cumin', 'coriander', 'oil'], 'description': 'A popular vegetarian dish made with potatoes and cauliflower, cooked with spices.', 'recipe': '1. Sauté cumin seeds in oil. 2. Add onion, ginger, and garlic and cook until golden. 3. Add tomatoes and spices. 4. Add potato and cauliflower florets. 5. Cover and cook until vegetables are tender.'},
        {'name': 'Dal Makhani', 'cuisine': 'northIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnOjZ_3Zdgar550bswU5dbFRVGb74Fuy1J8g&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 60, 'ingredients': ['urad dal', 'rajma', 'butter', 'cream', 'tomato', 'onion', 'ginger', 'garlic', 'garam masala'], 'description': 'A classic North Indian dish made with whole black lentils, red kidney beans, butter, and cream.', 'recipe': '1. Pressure cook soaked lentils and beans until soft. 2. Prepare a masala with onion, tomato, ginger, and garlic. 3. Combine the cooked lentils with the masala. 4. Simmer for at least 30 minutes, adding butter and cream. 5. Garnish and serve hot.'},
        {'name': 'Kofta', 'cuisine': 'northIndian', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpJs8plAp5OZA3BxucaY8JEoC-HNJW_fXREg&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 50, 'ingredients': ['potato', 'paneer', 'onion', 'tomato', 'cream', 'cashews', 'garam masala', 'corn flour', 'oil'], 'description': 'Savory balls made of minced vegetables or meat, simmered in a rich and flavorful gravy.', 'recipe': '1. Make kofta balls from mashed potato, paneer, and spices. 2. Deep fry the koftas until golden. 3. Prepare a gravy with onion, tomato, and cashew paste. 4. Add spices and cream to the gravy. 5. Add the koftas just before serving.'}
    ],
    'gujarati': [
        {'name': 'Dhokla', 'cuisine': 'gujarati', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3b-5dFm_ksE3zZt3oVzOq_wJ6B8XJ-gH_wA&usqp=CAU', 'meal_type': ['breakfast', 'snack'], 'cooking_time': 25, 'ingredients': ['chickpea flour', 'yogurt', 'semolina', 'ginger', 'green chili', 'turmeric', 'eno', 'mustard seeds', 'curry leaves', 'sugar', 'lemon juice'], 'description': 'A soft and spongy steamed cake made from fermented chickpea batter.', 'recipe': '1. Mix chickpea flour, yogurt, and water to a smooth batter. 2. Add ginger-chili paste, turmeric, and salt. 3. Just before steaming, add Eno fruit salt and mix. 4. Steam for 15-20 minutes. 5. Prepare a tempering of mustard seeds and curry leaves and pour over the dhokla.'},
        {'name': 'Thepla', 'cuisine': 'gujarati', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9f-v8a-7gZ-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['breakfast', 'lunch', 'snack'], 'cooking_time': 20, 'ingredients': ['whole wheat flour', 'fenugreek leaves', 'yogurt', 'turmeric', 'red chili powder', 'ginger', 'green chili', 'oil'], 'description': 'A soft, spiced flatbread made from whole wheat flour and fenugreek leaves.', 'recipe': '1. Knead a soft dough with whole wheat flour, chopped fenugreek leaves, yogurt, and spices. 2. Roll out thin circles. 3. Cook on a hot griddle with a little oil until both sides have golden brown spots. 4. Serve hot with yogurt or pickle.'}
    ],
    'fastFood': [
        {'name': 'Veggie Pizza', 'cuisine': 'fastFood', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5y-7zX-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 25, 'ingredients': ['all-purpose flour', 'yeast', 'sugar', 'salt', 'tomato sauce', 'mozzarella cheese', 'onion', 'bell pepper', 'mushroom', 'olives'], 'description': 'A classic favorite with a crispy crust, tangy tomato sauce, and a variety of vegetable toppings.', 'recipe': '1. Prepare the pizza dough and let it rise. 2. Roll out the dough and top with tomato sauce. 3. Add a generous layer of mozzarella cheese and your favorite vegetable toppings. 4. Bake in a preheated oven at 220°C (425°F) for 15-20 minutes.'},
        {'name': 'Veggie Burger', 'cuisine': 'fastFood', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5y-7zX-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 20, 'ingredients': ['burger buns', 'potato', 'peas', 'carrot', 'beans', 'bread crumbs', 'onion', 'tomato', 'lettuce', 'mayonnaise'], 'description': 'A satisfying burger with a hearty vegetable patty, fresh veggies, and creamy sauces.', 'recipe': '1. Create patties from boiled vegetables, spices, and bread crumbs. 2. Pan-fry or bake the patties until golden. 3. Toast the burger buns. 4. Assemble the burger with the patty, lettuce, tomato, onion, and mayonnaise.'}
    ],
    'chinese': [
        {'name': 'Veg Manchurian', 'cuisine': 'chinese', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5y-7zX-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 40, 'ingredients': ['cabbage', 'carrot', 'beans', 'all-purpose flour', 'corn flour', 'soy sauce', 'vinegar', 'ginger', 'garlic', 'onion', 'bell pepper'], 'description': 'Crispy fried vegetable balls tossed in a tangy and savory Manchurian sauce.', 'recipe': '1. Make vegetable balls from grated veggies and flour, then deep fry them. 2. In a pan, sauté ginger, garlic, and onion. 3. Add soy sauce, vinegar, and a corn flour slurry to make the sauce. 4. Add the fried vegetable balls and toss to coat.'},
        {'name': 'Fried Rice', 'cuisine': 'chinese', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5y-7zX-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 20, 'ingredients': ['rice', 'carrot', 'beans', 'peas', 'bell pepper', 'soy sauce', 'vinegar', 'ginger', 'garlic', 'oil'], 'description': 'A classic Chinese dish with stir-fried rice and a mix of vegetables.', 'recipe': '1. Heat oil in a wok and sauté chopped ginger and garlic. 2. Add chopped vegetables and stir-fry on high heat. 3. Add cooked rice, soy sauce, and vinegar. 4. Mix well and serve hot.'}
    ],
    'mexican': [
        {'name': 'Veggie Tacos', 'cuisine': 'mexican', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5y-7zX-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['lunch', 'dinner'], 'cooking_time': 25, 'ingredients': ['taco shells', 'beans', 'corn', 'onion', 'tomato', 'lettuce', 'salsa', 'sour cream', 'cheddar cheese'], 'description': 'Crispy taco shells filled with a savory mix of beans, corn, and fresh toppings.', 'recipe': '1. Warm the taco shells. 2. Prepare the filling by cooking beans and corn with spices. 3. Fill the shells with the bean mixture. 4. Top with lettuce, chopped tomatoes, salsa, sour cream, and cheese.'},
        {'name': 'Quesadillas', 'cuisine': 'mexican', 'image': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5y-7zX-9eY-8Z-6X-8cK-9jZ-gH_wA&usqp=CAU', 'meal_type': ['lunch', 'dinner', 'snack'], 'cooking_time': 15, 'ingredients': ['tortillas', 'cheddar cheese', 'mozzarella cheese', 'onion', 'bell pepper', 'jalapenos', 'oil'], 'description': 'A simple yet delicious dish of tortillas filled with cheese and other ingredients, then grilled.', 'recipe': '1. Place a tortilla on a lightly oiled pan. 2. Sprinkle with cheese, chopped onion, bell pepper, and jalapenos. 3. Top with another tortilla and cook until golden brown on both sides and the cheese is melted.'}
    ]
}

for cuisine_type, dishes in data.items():
    dishes_collection.insert_many(dishes)


print("Database seeded successfully!")
